const fs = require('fs');
const path = require('path');
const chalk = require('chalk');

function template(filename) {
  const iconName = path.basename(filename, '.tsx');
  return `export { ${iconName} } from './svgComponents/${iconName}';`;
}
function generateExports() {
  console.log(chalk.green('Generating exports'));
  const svgsPath = path.resolve('src/svgComponents');

  const importLines = ['// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.\n'];
  const svgs = fs.readdirSync(svgsPath).filter((filename) => path.extname(filename) === '.tsx');
  svgs.forEach((filename) => {
    const output = template(filename);
    importLines.push(output);
  });
  const outputPath = path.resolve('src', 'index.ts');
  fs.writeFileSync(outputPath, importLines.join('\n'));
}

module.exports = generateExports;
